name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: echo manish

    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}