name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification - Pipeline Started
        id: send_message
        run: |
          response=$(curl -X POST -H "Content-Type: application/json" -d '{
              "content": ":hourglass_flowing_sand: Pipeline Started"
          }' "${{ secrets.DISCORD_WEBHOOK }}")

          # Extract the message ID from the response
          message_id=$(echo $response | jq -r '.id')
          echo "Message ID: $message_id"
          echo "::set-output name=message_id::$message_id"

      - name: Build Your Project
        run: |
          # Your build commands go here
          echo "Building the project..."

      - name: Update Discord - Pipeline Completed
        run: |
          curl -X PATCH -H "Content-Type: application/json" -d '{
              "content": ":white_check_mark: Pipeline Completed Successfully! :100: Progress: 100%"
          }' "${{ secrets.DISCORD_WEBHOOK }}/messages/${{ steps.send_message.outputs.message_id }}"