name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    env:
      ENV_PATH: /home/ubuntu/.env
    steps:
      - name: Send Initial Notification to Discord
        id: discord_message
        run: |
          # Send the initial message to Discord and capture the response
          response=$(curl -X POST -H "Content-Type: application/json" -d '{
              "content": "Pipeline :rocket: Started on '${{ github.event_name }}' by :mechanic: '${{ github.actor }}'. Progress: :hourglass_flowing_sand: Initializing..."
          }' ${{ secrets.DISCORD_WEBHOOK }})
          
          # Check if the response is empty or contains errors
          if [[ -z "$response" ]]; then
            echo "Error: No response received from Discord webhook"
            exit 1
          fi

          # Extract the message ID from the response for future updates
          message_id=$(echo $response | jq -r .id)

          if [[ "$message_id" == "null" ]]; then
            echo "Error: Could not extract message ID"
            exit 1
          fi

          # Store the message_id as an environment variable for later use
          echo "message_id=$message_id" >> $GITHUB_ENV

      - name: Update Discord with Progress - Building
        run: |
          curl -X PATCH -H "Content-Type: application/json" -d '{
              "content": ":tools: Building... :hourglass_flowing_sand: Progress: 25%"
          }' ${{ secrets.DISCORD_WEBHOOK }}/messages/${{ env.message_id }}

      - name: Update Discord with Progress - Server Setup Complete
        run: |
          curl -X PATCH -H "Content-Type: application/json" -d '{
              "content": ":jigsaw: Server Setup Complete :hourglass_flowing_sand: Progress: 50%"
          }' ${{ secrets.DISCORD_WEBHOOK }}/messages/${{ env.message_id }}

      - name: Update Discord with Progress - Service Setup
        run: |
          curl -X PATCH -H "Content-Type: application/json" -d '{
              "content": ":gear: Setting up Service :hourglass_flowing_sand: Progress: 75%"
          }' ${{ secrets.DISCORD_WEBHOOK }}/messages/${{ env.message_id }}

      - name: Update Discord - Pipeline Completed
        run: |
          curl -X PATCH -H "Content-Type: application/json" -d '{
              "content": ":white_check_mark: Pipeline Completed Successfully! :100: Progress: 100%"
          }' ${{ secrets.DISCORD_WEBHOOK }}/messages/${{ env.message_id }}